### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by hazeycode** [leroycep/chrono-zig#5]
Could you apply a license to this library?
Public Domain code will inhibit usage in some projects because the copyright laws regarding Public Domain works varies by international jurisdictions.

**Comment by leroycep** [comment]
I'm planning on using the MIT license, or copying chrono's dual MIT/Apache license.

**Comment by leroycep** [comment]
Added MIT license in commit 91dc66ace59735f4a5aa637fdaa34a9b2cdf9231
